<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="./deco/css/cocktails0.css">

    
    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
</head>
<body class="container-fluid">

    <nav class="bandeau">
        <a href="index.php">Accueil</a>
        <a href="ajoutcoc.php">Ajout cocktail...</a>
        <a href="ajout_ingredient.php">Ajout ingredient...</a>
        <a href="deconsess.php">Deconnexion</a>
    </nav>

    <div class="kiss">
            <h1>Mister Cocktail</h1>
            <img src="./deco/images/bouche.gif" alt="kiss">
</div>
   
 <!-- Listing de tous les cocktails -->
 <p><strong>Ci-dessous, gestion des cocktails :</strong></p> 
        <br>   
    <main>

    <table class='table table_striped'>
   
    <thead>
        <tr>
            <th>#</th>
            <th>Nom</th>
            <th>description</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($cocktails as $cocktail){ ?>
        <tr>
            <td><?= $cocktail['id'] ?></td>
            <td><?= $cocktail['nom'] ?></td>
            <td><?= $cocktail['description'] ?></td>
            <td><a class="modsuppr" href="EDITION_COC.php?id=<?= $cocktail['id']?>">Modification</a></td>
            <td><a class="modsuppr" href="SuppBO.php?id=<?= $cocktail['id'] ?>">suppression</a></td>
        </tr>
        <?php } ?>
    </tbody>
</table>

    
    
    </table>         
   
    </main>
</body>
</html>

    </main>
</body>
</html>