<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="./deco/css/cocktails0.css">
</head>
<body class="container-fluid">
    <?php include 'templates/include/menu.php'; ?>
    <h1>Mister Cocktail</h1>

    <main>
       <form  method="POST" action="login.php">
           Login : <input type="text" name="login"><br></br>
           Password : <input type="password" name="password"><br></br>
           <input type="submit" value="Connexion">
       </form>
    </main>
</body>
</html> 